PXT.cwd("macros")

dofile("compile.lua")
dofile("test_preprocessor.lua")
os.exit(0)

print("Compiling macros...")
dofile("asm_macros.lua")

print("Done compiling macros.")
PXT.cwd("../")
compile_directory()
PXT.cwd("basics")
print("Compiling basics...")
compile_directory()
PXT.cwd("../")
PXT.cwd("data_flow")
print("Compiling data_flow...")
compile_directory()
PXT.cwd("../")
PXT.cwd("named_and_column_events")
print("Compiling named_column_events...")
compile_directory()
PXT.cwd("../")
PXT.cwd("state_machine")
print("Compiling state_machine...")
compile_directory()
PXT.cwd("../")
PXT.cwd("unit_tests")
print("Compiling unit_tests...")

compile_directory()
PXT.cwd("../")

os.exit(0)
